## Code Linting
name: Code Linting
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Linting Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff --no-deps

      - name: Show Files To Be Linted
        run: ruff check --show-files

      - name: Ruff Statistics
        run: ruff check --statistics
        continue-on-error: true

      - name: Ruff Check Grouped Format
        run: ruff check --output-format=grouped
